# Generated by Django 4.2.16 on 2025-05-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_teacherprofile_user_deanprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='enrollment_number',
            field=models.CharField(default='N/A', max_length=50, unique=True),
        ),
    ]
