# Generated by Django 5.2.1 on 2025-07-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_leaveapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_forwarded_by_dean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
