# Generated by Django 5.2.1 on 2025-05-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(related_name='subjects', to='users.teacherprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('name', 'course', 'session')},
        ),
    ]
