# Generated by Django 5.2.1 on 2025-05-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('name', 'course', 'session'), name='unique_semester_combo'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('course', 'session', 'order'), name='unique_semester_order'),
        ),
    ]
