# Generated by Django 4.2.16 on 2025-05-24 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teacherprofile'),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teachers',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacherprofile'),
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
