# Generated by Django 4.2.16 on 2025-05-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_teacherprofile_user_deanprofile'),
        ('academics', '0003_remove_subject_teachers_subject_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='users.teacherprofile'),
        ),
    ]
