# Generated by Django 4.2.16 on 2025-05-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_teacherprofile_user_deanprofile'),
        ('academics', '0004_remove_subject_teacher_subject_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(related_name='subjects', to='users.teacherprofile'),
        ),
    ]
