# Generated by Django 4.2.16 on 2025-05-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_subject_teachers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='semester',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
