# Generated by Django 4.2.16 on 2025-05-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_semester_options_semester_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
